### ISSUE TITLE
&amp; appears to be tokenized wrong in sets F, G, H

### ISSUE THREAD

**Issue by mayhewsw** [GateNLP/broad_twitter_corpus#6]
Shows up in sets F, G, H. It seems that if there was an \&amp; in the original text, it messes with the tokenization. The following words in the sentence are tokenized wrong also.

Find the errors with: 

```
>> grep -r "mp;" *.conll
```

**Comment by mayhewsw** [comment]
Set A and B tokenize \&lt; and \&gt; into "& lt ;" and "& gt ;". Is this intentional?

**Comment by mayhewsw** [comment]
The problem appears to be because the `annotation_offsets` field in the corresponding json file has character offsets for text where "&amp;" should be one character (namely, "&"). 

Try the following code:
```python
import json
import html
with open("g.json") as f:
    jslines = f.readlines()

for jsline in jslines:
    jsline = jsline.strip()
    js = json.loads(jsline)
    text = js["text"]

    if "&" not in text:
        continue
    
    offsets = js["annotation_offsets"]
    
    text_fixed = html.unescape(text)
    
    print("twitter.com/{}/status/{}".format(js["user"]["screen_name"], js["id"]))
    print(text)
    print(" ".join([text[o[0]:o[1]] for o in offsets]))
    print(" ".join([text_fixed[o[0]:o[1]] for o in offsets]))
    print()
```

**Comment by leondz** [comment]
Thanks. The tokenization was done different in sets A and B. This is definitely a bug though, especially in EFGH - we'll get a fix up.
